// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RiseTechnology.Entities.Context;

namespace RiseTechnology.Entities.Migrations
{
    [DbContext(typeof(RiseTechContext))]
    [Migration("20220201173956_Mg_Database_01")]
    partial class Mg_Database_01
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("RiseTechnology.Entities.Concrete.KISI", b =>
                {
                    b.Property<Guid>("ObjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Ad")
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)");

                    b.Property<int?>("Du_KullaniciID")
                        .HasColumnType("integer");

                    b.Property<bool>("Durum")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("DuzeltmeTarih")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FirmaBilgi")
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)");

                    b.Property<int?>("Ka_KullaniciID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("KayitTarih")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("Sil_KullaniciID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SilmeTarih")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Soyad")
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)");

                    b.HasKey("ObjectID");

                    b.ToTable("KISILER");
                });

            modelBuilder.Entity("RiseTechnology.Entities.Concrete.KISI_ILETISIM_BILGI", b =>
                {
                    b.Property<Guid>("ObjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Du_KullaniciID")
                        .HasColumnType("integer");

                    b.Property<bool>("Durum")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("DuzeltmeTarih")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Icerik")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int>("IletisimBilgiTip")
                        .HasColumnType("integer");

                    b.Property<int?>("Ka_KullaniciID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("KayitTarih")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("KisiID")
                        .HasColumnType("uuid");

                    b.Property<int?>("Sil_KullaniciID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SilmeTarih")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("ObjectID");

                    b.HasIndex("KisiID");

                    b.ToTable("KISI_ILETISIM_BILGILER");
                });

            modelBuilder.Entity("RiseTechnology.Entities.Concrete.RAPOR", b =>
                {
                    b.Property<Guid>("ObjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Du_KullaniciID")
                        .HasColumnType("integer");

                    b.Property<bool>("Durum")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("DuzeltmeTarih")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("Ka_KullaniciID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("KayitTarih")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("RaporDurumBilgi")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RaporTalepTarih")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("Sil_KullaniciID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SilmeTarih")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("ObjectID");

                    b.ToTable("RAPORLAR");
                });

            modelBuilder.Entity("RiseTechnology.Entities.Concrete.KISI_ILETISIM_BILGI", b =>
                {
                    b.HasOne("RiseTechnology.Entities.Concrete.KISI", "Kisi")
                        .WithMany()
                        .HasForeignKey("KisiID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kisi");
                });
#pragma warning restore 612, 618
        }
    }
}
