// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RiseTechnology.Entities.Context;

namespace RiseTechnology.Entities.Migrations
{
    [DbContext(typeof(RiseTechContext))]
    partial class RiseTechContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RiseTechnology.Entities.Concrete.Kisi", b =>
                {
                    b.Property<Guid>("ObjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ad")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<bool>("Durum")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DuzeltmeTarih")
                        .HasColumnType("datetime");

                    b.Property<int?>("Duzenleyen_KullaniciID")
                        .HasColumnType("int");

                    b.Property<string>("FirmaBilgi")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<int?>("Kaydeden_KullaniciID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("KayitTarih")
                        .HasColumnType("datetime");

                    b.Property<int?>("Silen_KullaniciID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SilmeTarih")
                        .HasColumnType("datetime");

                    b.Property<string>("Soyad")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("ObjectID");

                    b.ToTable("KISILER");
                });

            modelBuilder.Entity("RiseTechnology.Entities.Concrete.Kisi_Iletisim_Bilgi", b =>
                {
                    b.Property<Guid>("ObjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Durum")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DuzeltmeTarih")
                        .HasColumnType("datetime");

                    b.Property<int?>("Duzenleyen_KullaniciID")
                        .HasColumnType("int");

                    b.Property<string>("Icerik")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("IletisimBilgiTip")
                        .HasColumnType("int");

                    b.Property<int?>("Kaydeden_KullaniciID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("KayitTarih")
                        .HasColumnType("datetime");

                    b.Property<int?>("Silen_KullaniciID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SilmeTarih")
                        .HasColumnType("datetime");

                    b.HasKey("ObjectID");

                    b.ToTable("KISI_ILETISIM_BILGILER");
                });

            modelBuilder.Entity("RiseTechnology.Entities.Concrete.Rapor", b =>
                {
                    b.Property<Guid>("ObjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Durum")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DuzeltmeTarih")
                        .HasColumnType("datetime");

                    b.Property<int?>("Duzenleyen_KullaniciID")
                        .HasColumnType("int");

                    b.Property<int?>("Kaydeden_KullaniciID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("KayitTarih")
                        .HasColumnType("datetime");

                    b.Property<int>("RaporDurumBilgi")
                        .HasColumnType("int");

                    b.Property<DateTime>("RaporTalepTarih")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Silen_KullaniciID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SilmeTarih")
                        .HasColumnType("datetime");

                    b.HasKey("ObjectID");

                    b.ToTable("RAPORLAR");
                });
#pragma warning restore 612, 618
        }
    }
}
